[project]
name = "infomaid"
version = "0.20.2"
description = "@@A simple textual AI RAG application using Ollama for generative AI, chatting with PDFs AND chatting (querying) documents prepared in xml!"
authors = [
    {name = "Oliver Bonham-Carter",email = "obonhamcarter@allegheny.edu"}
]
readme = "README.md"
requires-python = ">=3.10.0,<4.0.0"
dependencies = [
    "typer (>=0.15.4,<0.16.0)",
    "rich (>=14.0.0,<15.0.0)",
    "black (>=25.1.0,<26.0.0)",
    "ollama (>=0.4.8,<0.5.0)",
    "pypdf (>=5.5.0,<6.0.0)",
    "chromadb (>=1.0.10,<2.0.0)",
    "pytest (>=8.3.5,<9.0.0)",
    "unstructured (>=0.17.2,<0.18.0)",
    "nltk (>=3.9.1,<4.0.0)",
    "langchain-community (>=0.3.24,<0.4.0)"
]

[tool.poetry]
packages = [{include = "infomaid", from = "src"}]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
infomaid = "infomaid.main:cli"

[tool.pytest.ini_options]
pythonpath = "infomaid"